/**
 * @domain marketing
 * @layer ui
 * @responsibility UI route entrypoint for /privacy
 */

import * as React from "react";
import type { Metadata } from "next"
import Link from "next/link"
import { AfendaIcon as BrandIcon } from "@afenda/marketing"

import {
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  Badge,
} from "@afenda/shadcn"
import { marketingRoutes } from "@afenda/marketing"

// Static generation with ISR (revalidate monthly)
export const revalidate = 2592000;

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy policy, data protection, and security practices powered by NexusCanon Infrastructure Fabric with SOC 2 Type II, HIPAA, GDPR, and CCPA compliance",
  alternates: {
    canonical: "/privacy",
  },
  openGraph: {
    title: "Privacy Policy - AFENDA",
    description: "Enterprise privacy policy powered by NexusCanon with SOC 2 Type II, HIPAA, GDPR, CCPA compliance. Military-grade encryption, RLS, and comprehensive audit trails.",
    type: "website",
    url: "/privacy",
  },
  twitter: {
    card: "summary",
    title: "Privacy Policy - AFENDA",
    description: "SOC 2, HIPAA, and GDPR compliant privacy practices with enterprise-grade security.",
  },
  robots: {
    index: true,
    follow: true,
  },
}

export default function PrivacyPage() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-16">
      <div className="w-full">
        <Card>
          <CardHeader className="space-y-3 text-center">
            <CardTitle className="text-2xl">Privacy Policy</CardTitle>
            <CardDescription>
              Effective date: {new Date().toLocaleDateString()} · Enterprise-grade privacy commitments powered by NexusCanon Infrastructure Fabric.
            </CardDescription>
            <div className="flex flex-wrap justify-center gap-2">
              <Badge variant="outline" className="gap-1">
                <BrandIcon className="h-3 w-3" aria-hidden="true" /> SOC 2 Type II
              </Badge>
              <Badge variant="outline" className="gap-1">
                <BrandIcon className="h-3 w-3" aria-hidden="true" /> HIPAA BAA
              </Badge>
              <Badge variant="outline" className="gap-1">
                <BrandIcon className="h-3 w-3" aria-hidden="true" /> GDPR + CCPA
              </Badge>
              <Badge variant="outline" className="gap-1">
                <BrandIcon className="h-3 w-3" aria-hidden="true" /> NexusCanon Engine
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="grid gap-8">
            <section className="grid gap-4 md:grid-cols-3">
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">We Do Not Sell Data</h3>
                <p className="text-muted-foreground mt-2">
                  Personal data is never sold or monetized. Processing is limited to service delivery and compliance needs.
                </p>
              </div>
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">Military-Grade Encryption</h3>
                <p className="text-muted-foreground mt-2">
                  AES-256-GCM encryption at rest, TLS 1.3 in transit, and hardware-backed key management protect all data layers.
                </p>
              </div>
              <div className="rounded-lg border p-4 text-sm">
                <h3 className="font-semibold">Retention Controls</h3>
                <p className="text-muted-foreground mt-2">
                  Account data is retained while active and removed within 30 days after closure, subject to legal obligations.
                </p>
              </div>
            </section>
            <div className="space-y-4 text-sm">
              <section>
                <h3 className="font-semibold">Information We Collect</h3>
                <p className="text-muted-foreground">
                  We collect information you provide directly (such as account details and support requests) and
                  information generated by service usage (such as audit logs and operational metadata). All data is stored
                  securely in Neon serverless PostgreSQL with encryption controls.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Data Storage & Infrastructure</h3>
                <p className="text-muted-foreground">
                  Your data is powered by <strong>NexusCanon Infrastructure Fabric</strong> in the <strong>ap-southeast-1 (Singapore)</strong> region.
                  Our infrastructure is SOC 2 Type II certified, HIPAA compliant, and features:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>Military-grade encryption:</strong> AES-256-GCM at rest, TLS 1.3 in transit</li>
                  <li><strong>Continuous protection:</strong> Hourly snapshots with 30-day point-in-time recovery</li>
                  <li><strong>Elastic compute:</strong> Auto-scaling from 0.25-8 CU with scale-to-zero</li>
                  <li><strong>High availability:</strong> Multi-AZ deployment with automatic failover</li>
                  <li><strong>Connection pooling:</strong> 10,000+ concurrent logical sessions</li>
                  <li><strong>Branch-first safety:</strong> Instant copy-on-write database branches</li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">How We Use Your Information</h3>
                <p className="text-muted-foreground">
                  We use collected information to deliver and operate the service, maintain security, improve performance,
                  respond to support requests, and meet legal or compliance requirements.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Legal Bases for Processing</h3>
                <p className="text-muted-foreground">
                  Where applicable, we process data based on contractual necessity, legitimate interests in operating a secure platform,
                  compliance with legal obligations, and user consent when required.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Information Sharing</h3>
                <p className="text-muted-foreground">
                  We do not sell personal information. We share data only with vetted subprocessors required to operate the service:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>NexusCanon Infrastructure:</strong> Core database engine (SOC 2 Type II, HIPAA, GDPR)</li>
                  <li><strong>Authentication Services:</strong> OAuth 2.0 and JWT-based identity management</li>
                  <li><strong>Cloud Infrastructure:</strong> Multi-region compute and storage providers</li>
                  <li><strong>CDN & Edge:</strong> Global content delivery and DDoS protection</li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">Data Security</h3>
                <p className="text-muted-foreground">
                  We implement layered security controls, including:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>Encryption:</strong> AES-256-GCM at rest, TLS 1.3 in transit, hardware-backed key management</li>
                  <li><strong>Authentication:</strong> OAuth 2.0 (Google, GitHub, Microsoft) with short-lived JWT tokens</li>
                  <li><strong>Access Control:</strong> Zero-trust RBAC, row-level security (RLS), and policy-based isolation</li>
                  <li><strong>Audit Logging:</strong> 365-day retention with immutable audit trails and compliance reporting</li>
                  <li><strong>Backup & Recovery:</strong> Hourly snapshots, 30-day PITR, cross-region replication</li>
                  <li><strong>Network Security:</strong> DDoS protection, WAF, and private networking options</li>
                </ul>
              </section>
              <section>
                <h3 className="font-semibold">Your Rights (GDPR & CCPA)</h3>
                <p className="text-muted-foreground">
                  You have the right to:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>Access:</strong> Request a copy of your personal data</li>
                  <li><strong>Rectification:</strong> Update or correct your information</li>
                  <li><strong>Erasure:</strong> Request deletion of your data (&quot;right to be forgotten&quot;)</li>
                  <li><strong>Portability:</strong> Export your data in a machine-readable format</li>
                  <li><strong>Objection:</strong> Opt-out of certain data processing activities</li>
                </ul>
                <p className="text-muted-foreground mt-2">
                  Contact <a href="mailto:legal@nexuscanon.com" className="underline">legal@nexuscanon.com</a> to exercise your rights.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">International Transfers</h3>
                <p className="text-muted-foreground">
                  Data may be processed in the regions where our infrastructure and subprocessors operate, including Singapore. We use
                  appropriate safeguards for cross-border transfers where required.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Data Retention</h3>
                <p className="text-muted-foreground">
                  We retain your data for as long as your account is active or as needed to provide services.
                  Deleted data is securely purged within 30 days using cryptographic erasure. Audit logs are retained for 365 days for compliance and forensic purposes, with immutable storage to prevent tampering.
                </p>
              </section>
              <section>
                <h3 className="font-semibold">Compliance & Certifications</h3>
                <p className="text-muted-foreground">
                  Our infrastructure meets the following standards:
                </p>
                <ul className="mt-2 list-inside list-disc space-y-1 text-muted-foreground">
                  <li><strong>SOC 2 Type II:</strong> Annual third-party audit covering security, availability, and confidentiality</li>
                  <li><strong>HIPAA:</strong> Business Associate Agreement (BAA) available for healthcare data</li>
                  <li><strong>GDPR:</strong> Full EU data protection compliance with data residency options</li>
                  <li><strong>CCPA:</strong> California Consumer Privacy Act compliance</li>
                  <li><strong>ISO 27001:</strong> Information security management certification (in progress)</li>
                  <li><strong>PCI DSS:</strong> Payment card industry compliance for financial data</li>
                </ul>
              </section>
            </div>
            <div className="flex flex-col gap-2">
              <Button asChild>
                <Link href={marketingRoutes.external.orchestra.root()}>Go to AFENDA</Link>
              </Button>
              <Button asChild variant="outline">
                <Link href={marketingRoutes.ui.security()}>View Security Declaration</Link>
              </Button>
              <Button asChild variant="ghost">
                <Link href={marketingRoutes.ui.terms()}>Terms of Service</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

